"""empty message

Revision ID: c58497ca7c03
Revises: 829a10f92f43
Create Date: 2020-05-10 18:45:16.352891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58497ca7c03'
down_revision = '829a10f92f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip', sa.Column('id', sa.Integer(), autoincrement=True, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip', 'id')
    # ### end Alembic commands ###
