version: "3.7"

services:

  flask:
    build: ./app
    container_name: flask
    networks:
      - default
    depends_on:
      - db
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/test
    restart: always
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

   db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    networks:
      - default
    ports:
      - 5436:5432
    restart: always
    #volumes:
    #  - ./postgres-data:/var/lib/postgresql/data