"""empty message

Revision ID: a36d58bb7ff0
Revises: c58497ca7c03
Create Date: 2020-05-10 18:45:55.804413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36d58bb7ff0'
down_revision = 'c58497ca7c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip', sa.Column('number', sa.Integer(), autoincrement=True, nullable=True))
    op.drop_column('ip', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ip', 'number')
    # ### end Alembic commands ###
